version: "3"
services:
  client:
    build: ./apps/client
    ports:
      - 80:5173
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    depends_on:
      - server
  server:
    build: ./apps/server
    ports:
      - 9999:9999
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    env_file:
      - .env
