version: "3"
services:
  server:
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    env_file:
      - .env
  client:
    build: ./client
    ports:
      - 80:5173
    volumes:
      - ./client:/app
      - /app/node_modules
  express:
    build: ./express
    ports:
      - 9999:9999
    volumes:
      - ./express:/app
      - /app/node_modules
    env_file:
      - .env
