version: "3"
services:
  client:
    build: ./client
    ports:
      - 80:5173
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build: ./server
    ports:
      - 9999:9999
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
